### ISSUE TITLE
last minute corner cases for 3.2

### ISSUE THREAD

**Issue by kaniini** [ircv3/ircv3-specifications#116]
*This is a whiteboard which lists technical defects with the 3.2 specification and their remediation status.  If all items are checked off, the bug may still remain open to track future defects until ratification is complete.*

- [x] sasl-reauth (#115)
- [x] metadata changes (#121)
  - [x] require `metadata-notify` for METADATA notifications via `MONITOR`
  - [x] update metadata spec to redistribute metadata for channels to channel users via `metadata-notify` cap
  - [x] add channel namespace to metadata
- [x] `cap-notify` ambiguity between 3.1 and 3.2 (#119, #120)
- [x] push `intents` draft back to 3.3 core specification (#118) 
- [x] `MONITOR` changes (#117)
  - [x] explain `MONITOR` vs `WATCH` (basically removal of numeric spam)
- [x] remove `=caps` and `~caps` instead enforcing serverside (#122)
- [x] last minute copyediting on metadata spec (#123)
- [x] message tags and `\0` (#128)
- [x] fix `self-message` vs. vendor-specific enhancements (seems no vendor likes `self-message`) (#135, #136)
- [x] more metadata cleanups (#131)

**Comment by dequis** [comment]
close?

**Comment by Shawn-Smith** [comment]
It'd be nice to advertise the length of message-tags somewhere, instead of hard-limiting to 512 characters, a token in the 005 numeric would be sufficient `TAGLEN=`.

Otherwise we're stuck with 512 bytes for as long as message-tags exist in the current format.

**Comment by kaniini** [comment]
@Shawn-Smith the current format is a stop-gap.  JSON transport will eventually replace it.

**Comment by kaniini** [comment]
@Shawn-Smith also that will not work because some caps enable message tags prior to 005.

**Comment by Shawn-Smith** [comment]
Hopefully JSON will eventually replace it, but it would be nice to advertise this just in case JSON doesn't happen for a long time. 

If the 005 wont work it could be advertised in the same manner that SASL mechanisms are advertised. Like message-tags=512 or something.

**Comment by SaberUK** [comment]
@Shawn-Smith Variable length message tags will make C (aka 99% of implementations) clients sad. 512 is enough.

**Comment by kaniini** [comment]
@Shawn-Smith perhaps we consider the limitation intentional in order to push JSON transport? :)

**Comment by Shawn-Smith** [comment]
I suppose, it seems a bit sketchy to intentionally limit a specification to push something that may never happen though.

@SaberUK I don't see how variable length tags differ from variable length everything else in the 005 numeric. Surely if they can do variable length topic/channel length/etc, they can do this too.

**Comment by DarthGandalf** [comment]
Topic length is variable, but still limited by message size 512.

2015-03-16 21:33 GMT+00:00 Shawn Smith <notifications@github.com>:
