### ISSUE TITLE
STS tracker

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#242]
Current status: https://github.com/ircv3/ircv3-specifications/blob/master/core/sts-3.3.md

## PRs

* [x] #184 Add requirements for long-lived connections (needs more client implementation input)
* [x] #249 Clarify server compliance requirements and policy deletion/rejection
* [x] #257 Add considerations for offering multiple IRC servers on the same domain
* [x] #261 Document relationship with STARTTLS and cap tls
* [x] #267 Add a DoS example for 3rd party CNAMEs

**Comment by attilamolnar** [comment]
#184 and #249 are mostly done. #210 and #243 are not related to sts directly.

**Comment by kylef** [comment]
I've created https://github.com/ircv3/ircv3-specifications/pull/263 and I'd love for this to make it into STS.

**Comment by jwheare** [comment]
All items complete. Moved related non-blockers to #269
