### ISSUE TITLE
Metadata tracker

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#244]
- [ ] **PR** #250 New spec with explicit key subscriptions
  - [ ] **Issue** #278 Additional non-normative sections
  - [ ] **PR** #245 Rate limiting (needs rebasing on #250 after that gets merged)
- [ ] **Issue** #228 Key registry

## Additional proposals
- [ ] **Issue** #173 Lists in metadata

## Closed
- [x] #219 Initial issue discussing problems with 3.2 spec
- [x] #279 Deprecate metadata-3.2

**Comment by attilamolnar** [comment]
https://github.com/ircv3/ircv3-specifications/compare/master...attilamolnar:metadata-flood

**Comment by Aerdan** [comment]
#173 pretty much isn't going to happen; values are free-form UTF-8, so it's entirely dependent on the key as to whether it's a list or not.

**Comment by jwheare** [comment]
* Persistence: my view is that there should be no expectation of persistence at all with metadata, just as there currently isn't with away status, realname, hostname, user, ident, nick, etc. Services/IRCds might well build an extra persistence layer, just as they have with NickServ/ChanServ/etc, but that layer is proprietary, and outside the scope of this spec.

* Moderation: Yes, a non-normative section should be added with recommendations for servers to handle this alongside their existing moderation tools, e.g. /spamfilter, extbans, etc. Again, it's a proprietary concern for now.

* I'd much favour letting clients specify keys on METADATA SYNC than the PRIORITY suggestion. Allowing clients to make simple explicit requests, rather than wrangle complex generalised systems.

**Comment by jwheare** [comment]
Closing in favour of the [metadata](https://github.com/ircv3/ircv3-specifications/labels/metadata) label and individual roadmapped issues.
