### ISSUE TITLE
Message ids, grouping and references

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#246]
## Issues
- [ ] #197 Batch type for longer messages (batch type)
- [ ] #208 Multi-line messages (batch type)
- [ ] ircv3/ircv3-ideas#1 Seen message notifications
## PRs:
- [x] #162 Labeled replies (client supplied tag, echoed in response, useful for echo-message, whois, etc)
- [x] #285 Server supplied message IDs
- [x] #288 Reply tag

**Comment by jwheare** [comment]
Closing this because the rest are still in the ideas stage and we have labels now.
