### ISSUE TITLE
Intents/CTCP/NOTICE replacement tracker

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#247]
Current published work in progress status: http://ircv3.net/specs/core/message-intents-3.3.html

Intents mix up a lot of different issues, a CTCP replacement, presentational tags, etc. There may be good and bad ideas in all of these.

As far as I can tell, there has been little interest in implementing the current 3.3 draft spec, and the original author has reverse their opinion on them, so it's possible it should be reversed out. Please comment if this assumption is incorrect.

## Issues:

* [ ] #138 Merge NOTICE and PRIVMSG into MESSAGE and replace with intents
* [ ] #163 Intent version of IRCX whisper
* [ ] #196 Intent capitalization
* [ ] #237 Nickname masquerading

## PRS:

* [ ] #58 Inquiries (e.g. CTCP TIME/PING)
* [ ] #238 Intents as presentation tags

**Comment by jwheare** [comment]
Closing via #270
