### ISSUE TITLE
Security tracker

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#269]
Ideas for security enhancements at the protocol level.
- [ ] #210 OOB distribution of cert fingerprints 
- [ ] #243 Public key pinning
- [ ] #266 Support setting an STS policy for multiple hostnames
- [ ] #263 Certificate transparency
- [ ] #295 Add the preload key

**Comment by jwheare** [comment]
Closing in favour of the [security](https://github.com/ircv3/ircv3-specifications/labels/security) label.
