### ISSUE TITLE
Jan 25 meeting – CAP 3.2 update todo

### ISSUE THREAD

**Issue by grawity** [ircv3/ircv3-specifications#34]
Updates to IRCv3 capability specification and `sasl` extension were discussed; this is my TODO list for updating the actual text:

CAP 3.2:

- [x] note that client may use CAP at any time, even after registration (to annoy euIRC)
- [x] re-add [multi-line `CAP LS * caps…`][draft-ls] from draft-mitchell-irc-capabilities-02
- [x] add either `CAP NEW caps…` or `CAP LS + caps…` to announce newly available capabilities (syntax depends on whether multi-line LS is approved)
- [x] note that ircd should use `CAP ACK -caps…` to announce capabilities no longer available (#33)
- [x] decide if it's actually `CAP ACK -caps…` or `CAP DEL caps…`
- [x] allow caps with values (`sasl=PLAIN,EXTERNAL`)
- [x] Add account-msg

SASL updates:

- [ ] reauth (#103)
- [x] add missing numeric 908 to the spec
- [ ] note that clients should expect numeric 908 and reduce their mechanisms-to-try list according to it
- [ ] allow clients to use `AUTHENTICATE ?` to query for a mechanism list
- [x] document DH-BLOWFISH
- [x] document DH-AES
- [ ] &lt;Aerdan&gt; Oh, right. 'Make it actually look like a specification.'
- [ ] import [server spec](https://gist.github.com/grawity/8389307) to the repository
- [ ] mention that the capability is *sticky* if the user has authenticated
- [ ] mention for the mechanism inventors out there that new mechs should support authz as the SASL RFC says

Other 3.2:

- [x] ~~Batch limit specified at start of batch, limit to be maximum allowed messages in batch.~~

This has been removed, see #40.

[draft]: http://www.leeh.co.uk/draft-mitchell-irc-capabilities-02.html
[draft-ls]: http://www.leeh.co.uk/draft-mitchell-irc-capabilities-02.html#ls

**Comment by kaniini** [comment]
* note that clients should expect numeric 908 and reduce their mechanisms-to-try list according to it
* allow clients to use AUTHENTICATE ? to query for a mechanism list

these are deprecated...

* <Aerdan> Oh, right. 'Make it actually look like a specification.'

this is objective and i do not really think we need to worry about it.

* import server spec to the repository
* mention that the capability is sticky if the user has authenticated
* mention for the mechanism inventors out there that new mechs should support authz as the SASL RFC says

these are good questions, but offtopic.

we can close this issue out, as the only remaining sasl task is being coordinated on #103
